# Generated by Django 5.2.5 on 2025-08-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(unique=True)),
                ('cliente', models.CharField(max_length=120)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('vendedor', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SURTIDO', 'Surtido'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=15)),
                ('almacen', models.CharField(choices=[('1', 'Almacén 1'), ('2', 'Almacén 2'), ('MIXTO', 'Mixto')], max_length=10)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('metodo_entrega', models.CharField(choices=[('PAQUETERIA', 'Paquetería'), ('REPARTIDOR', 'Repartidor'), ('SUCURSAL', 'Recogen en Sucursal')], max_length=15)),
            ],
        ),
    ]
