# Generated by Django 5.2.4 on 2025-08-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_ordenitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenUIState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.BigIntegerField(db_index=True, unique=True)),
                ('is_finalizado', models.BooleanField(default=False)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordenitem',
            name='orden',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='OrdenItem',
        ),
    ]
