# Generated by Django 5.2.4 on 2025-08-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_ordenuistate_remove_ordenitem_orden_delete_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenuistate',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
