# Generated by Django 5.2.4 on 2025-08-28 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_ordenuistate_first_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='ordenuistate',
            name='error_comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordenuistate',
            name='error_resuelto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenuistate',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenuistate',
            name='error_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.empleadoresponsable'),
        ),
    ]
