# Generated by Django 5.2.4 on 2025-08-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_empleadoresponsable_ordenuistate_error_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenuistate',
            name='folio',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
